// <auto-generated />
using System;
using Ferreteria.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ferreteria.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250310010151_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Ferreteria.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Name");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Client", b =>
                {
                    b.Property<string>("Rut")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("rut");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Rut");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<DateTime?>("HiringDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("hiring_date");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("JobPosition")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_position");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.Property<string>("UserRut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_rut");

                    b.HasKey("Id");

                    b.HasIndex("UserRut")
                        .IsUnique();

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_stock");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<string>("SupplierRut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.HasIndex("SupplierRut");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("movement_date");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("movement_type");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.ToTable("inventory_movement", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Brand")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("brand");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MeasurementUnit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("measurement_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock");

                    b.Property<string>("SupplierRut")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_rut");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Code");

                    b.HasIndex("CategoryName");

                    b.HasIndex("SupplierRut");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("SupplierRut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_rut");

                    b.Property<int?>("Total")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("total");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SupplierRut");

                    b.ToTable("purchase", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.PurchaseProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("purchase_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.HasIndex("PurchaseId");

                    b.ToTable("purchase_product", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ClientRut")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_rut");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("total");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("ClientRut");

                    b.HasIndex("EmployeeId");

                    b.ToTable("sale", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.SaleProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.HasIndex("SaleId");

                    b.ToTable("sale_product", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Supplier", b =>
                {
                    b.Property<string>("Rut")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("rut");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Rut");

                    b.ToTable("supplier", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.User", b =>
                {
                    b.Property<string>("Rut")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("rut");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted")
                        .HasDefaultValueSql("0");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("update_by");

                    b.HasKey("Rut");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Ferreteria.Domain.Entities.User", "UserRutNavigation")
                        .WithOne("EmployeeIdNavigation")
                        .HasForeignKey("Ferreteria.Domain.Entities.Employee", "UserRut")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_employee_user");

                    b.Navigation("UserRutNavigation");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Ferreteria.Domain.Entities.Product", "ProductCodeNavigation")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_inventory_product");

                    b.HasOne("Ferreteria.Domain.Entities.Supplier", null)
                        .WithMany("Inventories")
                        .HasForeignKey("SupplierRut");

                    b.Navigation("ProductCodeNavigation");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("Ferreteria.Domain.Entities.Product", "IdProductNavigation")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_inventory_movement_product");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Product", b =>
                {
                    b.HasOne("Ferreteria.Domain.Entities.Category", "CategoryNameNavigation")
                        .WithMany("Products")
                        .HasForeignKey("CategoryName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_product_category");

                    b.HasOne("Ferreteria.Domain.Entities.Supplier", "SupplierRutNavigation")
                        .WithMany("Products")
                        .HasForeignKey("SupplierRut")
                        .HasConstraintName("FK_product_supplier");

                    b.Navigation("CategoryNameNavigation");

                    b.Navigation("SupplierRutNavigation");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("Ferreteria.Domain.Entities.Employee", "EmployeeIdNavigation")
                        .WithMany("Purchases")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_purchase_employee");

                    b.HasOne("Ferreteria.Domain.Entities.Supplier", "SupplierRutNavigation")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierRut")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_purchase_supplier");

                    b.Navigation("EmployeeIdNavigation");

                    b.Navigation("SupplierRutNavigation");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.PurchaseProduct", b =>
                {
                    b.HasOne("Ferreteria.Domain.Entities.Product", "ProductCodeNavigation")
                        .WithMany("PurchaseProducts")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_purchase_product_product");

                    b.HasOne("Ferreteria.Domain.Entities.Purchase", "PurchaseIdNavigation")
                        .WithMany("PurchaseProducts")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_purchase_product_purchase");

                    b.Navigation("ProductCodeNavigation");

                    b.Navigation("PurchaseIdNavigation");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Ferreteria.Domain.Entities.Client", "ClientRutNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("ClientRut")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_sale_client");

                    b.HasOne("Ferreteria.Domain.Entities.Employee", "EmployeeIdNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_sale_employee");

                    b.Navigation("ClientRutNavigation");

                    b.Navigation("EmployeeIdNavigation");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.SaleProduct", b =>
                {
                    b.HasOne("Ferreteria.Domain.Entities.Product", "ProductCodeNavigation")
                        .WithMany("SaleProducts")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_sale_product_product");

                    b.HasOne("Ferreteria.Domain.Entities.Sale", "SaleIdNavigation")
                        .WithMany("SaleProducts")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_sale_product_sale");

                    b.Navigation("ProductCodeNavigation");

                    b.Navigation("SaleIdNavigation");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Client", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Product", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryMovements");

                    b.Navigation("PurchaseProducts");

                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("PurchaseProducts");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Products");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Ferreteria.Domain.Entities.User", b =>
                {
                    b.Navigation("EmployeeIdNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
